# Generated by Django 6.0.4 on 2026-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
